<a href="https://colab.research.google.com/github/AbhishekChaganti/MY_REPO/blob/main/encoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['apple', 'banana', 'orange', 'carrot', 'tomato', 'potato']
item_types = ['fruit', 'fruit', 'fruit', 'vegetable', 'vegetable', 'vegetable']

le = LabelEncoder()
encoded_types = le.fit_transform(item_types)

print(item_types)
print(encoded_types)

data = np.array(['red', 'blue', 'green', 'blue', 'red']).reshape(-1,1)

oe = OneHotEncoder(sparse_output=False)
encoded_data = oe.fit_transform(data)

print('\n',encoded_data)

['fruit', 'fruit', 'fruit', 'vegetable', 'vegetable', 'vegetable']
[0 0 0 1 1 1]

 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
